spring.application.name=clini


spring.datasource.url=jdbc:postgresql://localhost:5432/clinic
spring.datasource.username=postgres
spring.datasource.password=pazofils

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true